### ISSUE TITLE
Massive code quality improvements

### ISSUE THREAD

**Issue by tangalbert919** [sayori34/dokis#63]
Things that we will need to do:

- [x] Split up the `events.py` file into multiple files.
- [x] Redo `if` statements and categorize them by doki and MC.
- [x] Remove Cheezy's comments.
- [x] Find a way to put the actual changelog in one file, and have the dokis read them.

**Comment by sayuri3** [comment]
I could have done cheezy comments but too late
RIP

**Comment by Cheezy096** [comment]
Big RIP

**Comment by tangalbert919** [comment]
Finished. I just need to go through this and look for bugs.

**Comment by tangalbert919** [comment]
All bugs that I could find were fixed. This, I can close now.
