### ISSUE TITLE
Remove eval from dokis

### ISSUE THREAD

**Issue by sayori34** [sayori34/dokis#72]
It's as the title says, I think we should remove eval from the dokis and mc due to security issues

**Comment by Cheezy096** [comment]
Why Eval was added i'm not even sure, anyway you could limit the eval function to just the person who hosts the doki's but then again that would be silly.

I'm trying to think of a way how Eval could be locked down.

**Comment by Cheezy096** [comment]
One thing you could do is when eval is run send a message to the terminal or just dm the developers or something with content such as "Eval command executed in (guild+channel)" "Executed at (time)" "Code run (code)",

**Comment by Cheezy096** [comment]
Though, removing the eval command would probably just relive the stress anyway. Your choice. Remove it or try to solve security issues by locking eval down. (I'm waiting for our buddy "tangalbert919" to delete my messages heh, i've come to expect it)

**Comment by tangalbert919** [comment]
As I have stated before, if you are going to spew bullshit, I'm going to delete it.

What I just read here is not bullshit, so you're fine.

I am already removing the eval command from all dokis, so don't worry about it.

**Comment by sayori34** [comment]
> As I have stated before, if you are going to spew bullshit, I'm going to delete it.
> What I just read here is not bullshit, so you're fine.
> I am already removing the eval command from all dokis, so don't worry about it.

Alright

**Comment by tangalbert919** [comment]
The bullshit part was directed to Cheezy, in case you were confused.

**Comment by tangalbert919** [comment]
Finished.
